angular
  .module('questions')
  .controller 'IndexController', ($scope, supersonic) ->

    $scope.current        = 1
    $scope.totalQuestions = 234
    $scope.options        = duration: 0.3 ; curve: "linear"
    $scope.questions      = {
      1: "I feel accepted"
      2: "I don’t feel accepted"
      3: "I know I am liked"
      4: "I feel understood"
      5: "I feel rejected"
      6: "I feel like you dislike me "
      7: "I feel misunderstood"
      8: "I feel appreciated"
      9: "I feel unappreciated"
      10: "I feel abandoned"
      11: "I feel connected"
      12: "I feel close to you"
      13: "I feel distant from you"
      14: "I feel comfortable"
      15: "I feel critical of you"
      16: "I feel uncomfortable"
      17: "I feel affectionate"
      18: "I feel tense"
      19: "I feel betrayed"
      20: "I feel like you don’t even like me"
      21: "I feel irritable"
      22: "I feel alienated"
      23: "I am angry"
      24: "I am agitated"
      25: "I am restless"
      26: "I feel alone"
      27: "I feel lonely"
      28: "I am upset"
      29: "I am alarmed"
      30: "I am afraid"
      31: "I feel like hitting something"
      32: "I feel like kicking something"
      33: "I am amused"
      34: "I am surprised"
      35: "I feel like arguing"
      36: "I appreciate you"
      37: "I feel like bragging"
      38: "I am anguished"
      39: "I feel like a failure"
      40: "I am ashamed"
      41: "I want to assert my rights"
      42: "I feel like an innocent victim"
      43: "I feel righteously indignant"
      44: "I am apprehensive"
      45: "I feel shy"
      46: "I am horny"
      47: "I feel romantic"
      48: "I feel unattractive"
      49: "I am not sure how I feel"
      50: "I am ambivalent"
      51: "I feel like apologizing"
      52: "I feel regretful"
      53: "I feel resentful"
      54: "I am astounded"
      55: "I feel awe"
      56: "I feel clumsy, awkward"
      57: "I feel belittled"
      58: "I feel insulted"
      59: "I want to be belligerent"
      60: "I feel bashful"
      61: "I feel battered"
      62: "I am baffled"
      63: "I feel beautiful"
      64: "I feel handsome"
      65: "I feel neglected"
      66: "I am bitter"
      67: "I am exhausted"
      68: "I have no energy"
      69: "I feel like boasting"
      70: "I am confused and bewildered"
      71: "I feel sad"
      72: "I am bored"
      73: "I just can’t get interested in anything right now"
      74: "I feel brave"
      75: "I feel like I have been defeated"
      76: "I feel unfairly labeled"
      77: "I feel burdened"
      78: "I am calm"
      79: "I feel competent"
      80: "I feel incompetent"
      81: "I feel cheerful"
      82: "I feel cheated"
      83: "I feel used"
      84: "I am feeling compassion"
      85: "I feel peaceful"
      86: "I feel competitive"
      87: "I feel condemned"
      88: "I feel confident"
      89: "I feel constrained"
      90: "I feel criticized"
      91: "I am crushed"
      92: "I feel conflicted"
      93: "I hate you"
      94: "I feel creative"
      95: "I feel confused"
      96: "I feel defeated"
      97: "I am delighted"
      98: "I am desperate"
      99: "I feel like giving up"
      100: "I feel sexual desire"
      101: "I am displeased"
      102: "I can’t believe this"
      103: "I feel disgraced"
      104: "I disapprove"
      105: "I feel superior"
      106: "I am distrustful"
      107: "I feel downhearted"
      108: "I feel dread"
      109: "I have no sexual desire at all"
      110: "I am eager"
      111: "I am ecstatic"
      112: "I feel embarrassed"
      113: "I feel empty"
      114: "I feel empathy"
      115: "I am preoccupied"
      116: "I am enraged"
      117: "I feel envious"
      118: "I feel euphoric"
      119: "I feel exposed"
      120: "I feel like being cruel"
      121: "I feel like hurting someone"
      122: "I feel fat"
      123: "I feel fit"
      124: "I am flattered"
      125: "I feel foolish"
      126: "I feel flustered"
      127: "I feel stupid"
      128: "I feel forsaken"
      129: "I feel lucky"
      130: "I am frantic"
      131: "I am frazzled"
      132: "I am furious"
      133: "Everything seems futile"
      134: "I feel generous"
      135: "I am grateful"
      136: "I am feeling grief"
      137: "I am happy"
      138: "I feel heartless, cold"
      139: "I feel hate"
      140: "I am honored "
      141: "I feel like being hostile"
      142: "I feel humble"
      143: "I am hurt"
      144: "I feel hysterical"
      145: "It’s too hot in here"
      146: "It’s too cold in here"
      147: "I feel sick"
      148: "I feel like an idiot"
      149: "I feel inadequate"
      150: "I feel indifferent"
      151: "I feel impatient"
      152: "I am impressed"
      153: "I feel indecisive"
      154: "I feel inept"
      155: "I feel insecure"
      156: "I feel jealous"
      157: "I feel invaded"
      158: "I feel intimidated"
      159: "I feel inspired"
      160: "I feel jittery"
      161: "I feel jumpy"
      162: "I feel relaxed"
      163: "I feel like being totally logical"
      164: "I feel left out"
      165: "I feel excluded"
      166: "I feel unimportant to you"
      167: "I feel lonesome"
      168: "I have a longing"
      169: "I am in love"
      170: "I feel lustful"
      171: "I feel mean"
      172: "I feel masterful"
      173: "I feel manipulated"
      174: "I feel melancholy"
      175: "I feel mature"
      176: "I feel like a child"
      177: "I feel mellow"
      178: "I am miffed"
      179: "I feel mischievous"
      180: "I feel mistreated"
      181: "I feel silly"
      182: "I feel needy"
      183: "I feel nostalgic"
      184: "I feel needed"
      185: "I feel numb"
      186: "I feel stubborn"
      187: "I feel on edge"
      188: "I am outraged"
      189: "I feel preoccupied"
      190: "I feel panicked"
      191: "How dare you!"
      192: "I feel perplexed"
      193: "I feel pessimistic"
      194: "I feel playful"
      195: "I feel possessive"
      196: "I am pleased"
      197: "I feel protective"
      198: "I feel put down"
      199: "I am hungry"
      200: "I feel scolded"
      201: "I feel respectful"
      202: "I feel reverent"
      203: "I feel irrelevant"
      204: "I want revenge"
      205: "I feel ridiculous"
      206: "I am tense"
      207: "I am worried"
      208: "I feel sexy"
      209: "I am shocked"
      210: "I feel spiteful"
      211: "I am stressed"
      212: "I feel stingy"
      213: "My talents aren’t being recognized"
      214: "I feel successful"
      215: "I have been unfairly judged"
      216: "I feel like pouting"
      217: "I feel vulnerable"
      218: "I am caught in someone’s web"
      219: "I want to take care of you"
      220: "I feel tearful"
      221: "I feel thankful"
      222: "I feel thrilled"
      223: "I feel tortured"
      224: "I feel undecided"
      225: "I am weary"
      226: "I feel witty"
      227: "I feel whimsical"
      228: "I feel wounded"
      229: "I feel disgusted"
      230: "I feel like throwing up"
      231: "I am not going to take any more"
      232: "I’ve had it!"
      233: "I feel trapped"
      234: "I feel smothered"
    }

    $scope.previousQuestion = () ->
      $scope.current -= 1
      $scope.current = $scope.totalQuestions if $scope.current < 1
      supersonic.ui.animate("slideFromLeft", $scope.options).perform()

    $scope.nextQuestion = () ->
      $scope.current += 1
      $scope.current = 1 if $scope.current > $scope.totalQuestions
      supersonic.ui.animate("slideFromRight", $scope.options).perform()

    $scope.currentQuestion = () -> $scope.questions[$scope.current]

    $scope.resetQuestions = () ->
      return if $scope.current == 1
      $scope.current = 1
      supersonic.ui.animate("slideFromLeft", $scope.options).perform()